# Generated by Django 6.0.1 on 2026-02-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount_text', models.CharField(help_text="E.g. '25% OFF' or '₹500 OFF'", max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Membership', 'Membership'), ('Training', 'Workshops'), ('Merchandise', 'Merchandise')], max_length=50)),
                ('color', models.CharField(default='#8B5E3C', help_text='Hex Code (e.g. #8B5E3C)', max_length=20)),
                ('icon_class', models.CharField(default='fa-gift', help_text='FontAwesome class (e.g. fa-gift)', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
