# Generated by Django 6.0.1 on 2026-02-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('Ceramics', 'Ceramics'), ('Wood', 'Woodwork'), ('Textiles', 'Textiles'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
