# Generated by Django 6.0.1 on 2026-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Tranquil Trails', max_length=100)),
                ('admin_email', models.EmailField(default='admin@tranquiltrails.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 234 567 890', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('shipping_flat_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
