# Generated by Django 6.0.2 on 2026-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Crafting Tranquility', max_length=200)),
                ('hero_subtitle', models.CharField(default='Sustainable Artistry for the Intentional Home', max_length=200)),
                ('hero_bg_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('philosophy_title', models.CharField(default='Our Philosophy', max_length=200)),
                ('philosophy_text_1', models.TextField(default='Tranquil Trails began with a simple mission...')),
                ('philosophy_text_2', models.TextField(blank=True)),
                ('philosophy_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('stat_1_number', models.CharField(default='100%', max_length=50)),
                ('stat_1_label', models.CharField(default='Handmade', max_length=50)),
                ('stat_2_number', models.CharField(default='50+', max_length=50)),
                ('stat_2_label', models.CharField(default='Local Artisans', max_length=50)),
                ('stat_3_number', models.CharField(default='Eco', max_length=50)),
                ('stat_3_label', models.CharField(default='Friendly', max_length=50)),
                ('founder_name', models.CharField(default='Malvaniya Meet', max_length=100)),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('founder_story_1', models.TextField(default='Growing up surrounded by artisans...')),
                ('founder_story_2', models.TextField(blank=True)),
                ('founder_quote', models.TextField(default='Art is not just what we make, but how we live.')),
                ('video_url', models.URLField(default='https://cdn.pixabay.com/video/2023/04/21/159256-821688076_large.mp4')),
            ],
            options={
                'verbose_name_plural': 'About Page Settings',
            },
        ),
    ]
